version: 2
jobs:
  build:
    docker:
      - image: circleci/android:api-29

    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx3200m

    steps:
      - checkout

      #- restore_cache:
      #    key: jars-{{ checksum "build.gradle" }}-{{ checksum  "showtime-client/app/build.gradle" }}

      - run: 
          name: Build 
          working_directory: ./showtime-client
          command: ./gradlew androidDependencies

      #- save_cache:
      #    paths:
      #      - ~/.gradle
      #    key: jars-{{ checksum "build.gradle" }}-{{ checksum  "showtime-client/app/build.gradle" }}

      - run: 
          name: Test
          working_directory: ./showtime-client
          command: ./gradlew lint test

      - store_artifacts: 
          path: showtime-client/app/build/reports
          destination: reports

      - store_test_results: 
          path: showtime-client/app/build/test-results
